### ISSUE TITLE
DirectDrawInvalidParametersException thrown when alt-tabbing and then navigating to a new scene.

### ISSUE THREAD

**Issue by sethballantyne** [sethballantyne/Game-Demos#42]
In the main menu, alt-tab so the game is minimized. Maximize the game, then navigate to another scene; a DirectDrawInvalidParametersException will be thrown. Here's the stack trace:

> Fatal Error: DirectDrawInvalidParametersException thrown. IDirectDrawSurface7::Blt: one or more of the parameters passed to the method are incorrect.
> 
> Stack trace:    at Video.Blit(Rectangle sourceRect, Rectangle destinationRect, Surface surface) in c:\projects\project ball buster\src\pbb\game\video.cpp:line 1352
>    at Font.Render(Int32 x, Int32 y, String text, Object[] args) in c:\projects\project ball buster\src\pbb\game\font.cpp:line 94
>    at Label.Render() in c:\projects\project ball buster\src\pbb\game\label.h:line 79
>    at MenuItem.Render() in c:\projects\project ball buster\src\pbb\game\menuitem.h:line 136
>    at MenuItemContainer.Render() in c:\projects\project ball buster\src\pbb\game\menuitemcontainer.h:line 172
>    at Scene.Render() in c:\projects\project ball buster\src\pbb\game\scene.h:line 149
>    at Game.Render() in c:\projects\project ball buster\src\pbb\game\game.cpp:line 135
>    at Game.Update() in c:\projects\project ball buster\src\pbb\game\game.cpp:line 175
>    at WinMain(HINSTANCE__* hInstance, HINSTANCE__* hPrevInstance, SByte* lpCmdLine, Int32 nCmdShow) in c:\projects\project ball buster\src\pbb\game\main.cpp:line 195
>

**Comment by sethballantyne** [comment]
the garbage collector was deleting the IDirectDrawSurface instance via the finalizer which I don't want it to do, ever so I removed it. The direct draw surface can be deleted via Surface::Release().
