### ISSUE TITLE
HighScores::GetPlayerName() throws ArgumentOutOfRangeException when highscores.dat is empty.

### ISSUE THREAD

**Issue by sethballantyne** [sethballantyne/Game-Demos#48]
When the highscores.dat is empty, it'd probably be a good idea to populate the list `highScores` with defaults to avoid this.

> [08/05/18 20:56:39] Fatal Error: System.ArgumentOutOfRangeException thrown. Specified argument was out of the range of valid values.
Parameter name: row
Stack trace: 
   at HighScores.GetPlayerName(UInt32 row) in c:\projects\project ball buster\src\pbb\game\highscores.h:line 105
   at HighScoreTable..ctor(Int32 x, Int32 y, Int32 numberOfRows, Int32 vertialSpacing, Int32 indexXPosition, String rowNumberFont, Int32 PlayerNameXPosition, String playerNameFont, Int32 scoreXPosition, String scoreFont) in c:\projects\project ball buster\src\pbb\game\highscoretable.cpp:line 106
   at SceneFactory.ParseHighScoreTable(XElement element) in c:\projects\project ball buster\src\pbb\game\scenefactory.cpp:line 212
   at SceneFactory.Read(XElement sceneXML) in c:\projects\project ball buster\src\pbb\game\scenefactory.cpp:line 365
   at SceneManager.Initialise(XElement scenesXML) in c:\projects\project ball buster\src\pbb\game\scenemanager.cpp:line 40
   at Game.Initialise(HINSTANCE__* hInstance, HWND__* hWnd) in c:\projects\project ball buster\src\pbb\game\game.cpp:line 106
   at WinMain(HINSTANCE__* hInstance, HINSTANCE__* hPrevInstance, SByte* lpCmdLine, Int32 nCmdShow) in c:\projects\project ball buster\src\pbb\game\main.cpp:line 175

**Comment by sethballantyne** [comment]
fixed in commit e27e7163800eeb90fa853a8b29e6277b305516db.
