### ISSUE TITLE
DirectX sub-systems don't always shutdown

### ISSUE THREAD

**Issue by sethballantyne** [sethballantyne/Game-Demos#53]
When an exception is thrown during execution, the sub-systems don't always shutdown; it looks like one of them is crashing. An example is changing one of the paths in paths.xml to a path that doesn't exist; when the resulting exception occurs, the following is logged to log.txt

```
[24/05/18 14:42:59] Initialising video
[24/05/18 14:42:59] Initialising audio
[24/05/18 14:42:59] Ininitialising input
[24/05/18 14:42:59] Loading the games settings.
[24/05/18 14:42:59] Ininitialising the resource manager.
[24/05/18 14:43:00] Fatal Error: System.IO.DirectoryNotFoundException thrown. the path /data/audio/abv doesn't exist or is invalid.
Stack trace: 
   at ResourceManager.ParsePaths(XElement resourceElement, List`1& pathList) in c:\projects\project ball buster\src\pbb\game\resourcemanager.cpp:line 93
   at ResourceManager.Initialise(String pathsFile) in c:\projects\project ball buster\src\pbb\game\resourcemanager.cpp:line 150
   at Game.Initialise(HINSTANCE__* hInstance, HWND__* hWnd) in c:\projects\project ball buster\src\pbb\game\game.cpp:line 106
   at WinMain(HINSTANCE__* hInstance, HINSTANCE__* hPrevInstance, SByte* lpCmdLine, Int32 nCmdShow) in c:\projects\project ball buster\src\pbb\game\main.cpp:line 175

[24/05/18 14:43:00] closing the high scores file
```

Neither the video, audio or input systems shutdown.

**Comment by sethballantyne** [comment]
0045b214793fe629916a338e64dc6d7d0728efc9 fixes this when an exception is thrown inside ResourceManager::ParsePaths(). I'm leaving this open in case the issue pops up elsewhere.
